name = "lean-practice"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanPractice"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
pp.fieldNotation = false
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.1"

[[lean_lib]]
name = "LeanPractice"
